#!/bin/sh
# Nginx runit service script
#
# Runs Nginx in foreground mode under runit supervision.
# Runit will automatically restart Nginx if it crashes.

templates=`find /etc/nginx -name '*.tmpl'`

for t in $templates; do
    conffile=`echo $t | sed 's,\.tmpl,,'`
    dockerize --template "${t}:$conffile"
done

exec /usr/sbin/nginx -g "daemon off;"
